# Generated by Django 2.2.6 on 2019-10-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='picture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
